<a href="https://colab.research.google.com/github/RapaDewan/Deep-Learning/blob/main/FCC_DL_00/FCC_DL_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.3.1+cu121'

In [ ]:
scaler=torch.tensor(8)
scaler


tensor(8)

In [ ]:
scaler.ndim

0

In [ ]:
scaler.item()

8

In [ ]:
vector=torch.tensor([7,7,8,9])
vector

tensor([7, 7, 8, 9])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([4])

In [ ]:
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR=torch.tensor([[[1,2,3],
                      [4,5,6],
                     [7,8,9]]])

In [ ]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.shape


torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim

3

In [ ]:
random_tensor=torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.0520, 0.7996, 0.2837, 0.1021],
         [0.7682, 0.5869, 0.6339, 0.6689],
         [0.2521, 0.2733, 0.7104, 0.6821]]),
 torch.float32)

In [ ]:
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros=torch.zeros(size=(3,3))
zeros, zeros.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32)

In [ ]:
ones=torch.ones(size=(3,3))
ones, ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

##Creating a range and tensors like¶


In [ ]:
zero_to_ten_dep=torch.range(0,10)
zero_to_ten_dep

<ipython-input-38-fb0c4d41fad7>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_dep=torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
zero_to_ten=torch.arange(start=0, end=10, step=2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [ ]:
five_zeros=torch.zeros_like(input=zero_to_ten)
five_zeros

tensor([0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)

float_16_tensor.dtype

torch.float16

##Getting information from tensors¶


In [ ]:
some_tensor = torch.rand(3, 4)
print(some_tensor)

print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.5002, 0.9379, 0.0637, 0.2791],
        [0.1608, 0.3077, 0.4257, 0.0593],
        [0.2699, 0.2520, 0.7827, 0.4745]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


##Manipulating tensors (tensor operations)


In [ ]:
tensor=torch.tensor([1,2,3])
tensor.ndim

1

In [ ]:
tensor+20

tensor([21, 22, 23])

In [ ]:
tensor*5


tensor([ 5, 10, 15])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [ ]:
tensor.add(tensor+10) #ekhane 11,12,13 ashlona kno?


tensor([12, 14, 16])

In [ ]:
print(tensor,'*', tensor)
print("Equals:", tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


##Matrix multiplication

In [ ]:
tensor=torch.tensor([1,2,3])

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor@ tensor

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 2.02 ms, sys: 0 ns, total: 2.02 ms
Wall time: 9.05 ms


tensor(14)

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

In [ ]:
print(tensor_A)
print(tensor_B)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,
                         out_features=6)
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


##Finding the min, max, mean, sum, etc (aggregation)¶


In [ ]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min()

tensor(0)

In [ ]:
x.max()

tensor(90)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
x.sum()

tensor(450)

In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)


(tensor(90), tensor(0), tensor(45.), tensor(450))

##Positional min/max¶


In [ ]:
tensor=torch.arange(10,100,10)
tensor

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
tensor.argmax()

tensor(8)

In [ ]:
tensor.argmin()

tensor(0)

In [ ]:
torch.argmax(tensor)

tensor(8)

##Change tensor datatype¶


In [ ]:
tensor_float16=tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
tensor_int8=tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [ ]:
x=torch.arange(1.,8.)
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
x.shape

torch.Size([7])

In [ ]:
x_reshaped=x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z=x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
x_stacked=torch.stack([x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.]])

In [ ]:
x_stacked=torch.stack([x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
x_sq=x_reshaped.squeeze()
x_sq, x_sq.shape

(tensor([5., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_unsq=x_sq.unsqueeze(dim=0)
x_unsq, x_sq.shape

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), torch.Size([7]))

In [ ]:
x_org=torch.rand(224,224,3)
x_permuted=x_org.permute(2,0,1)
x_org.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

##Indexing (selecting data from tensors)¶



In [ ]:
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0][0][2]

tensor(3)

In [ ]:
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:,2]

tensor([[5, 5, 5]])

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

##PyTorch tensors & NumPy¶


In [ ]:
import numpy as np

In [ ]:
array=np.arange(1.0, 8.0)
tensor=torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array=array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor= torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor=tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducibility (trying to take the random out of random)

In [ ]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A, random_tensor_B

(tensor([[0.8016, 0.3649, 0.6286, 0.9663],
         [0.7687, 0.4566, 0.5745, 0.9200],
         [0.3230, 0.8613, 0.0919, 0.3102]]),
 tensor([[0.9536, 0.6002, 0.0351, 0.6826],
         [0.3743, 0.5220, 0.1336, 0.9666],
         [0.9754, 0.8474, 0.8988, 0.1105]]))

In [ ]:
random_tensor_A==random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
import random

In [ ]:
RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

random_tensor_C, random_tensor_D,random_tensor_C==random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))